services:
  airflow:
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    restart: unless-stopped
    container_name: ${USER}-airflow-example
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    command: >
      bash -c "
        airflow scheduler & 
        airflow webserver -p 8080
      "